export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";

export const FETCH_CRYPTO_REQUEST = "FETCH_CRYPTO_REQUEST";
export const FETCH_CRYPTO_SUCCESS = "FETCH_CRYPTO_SUCCESS";
export const FETCH_CRYPTO_FAILURE = "FETCH_CRYPTO_FAILURE";
